# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "npm" # Or "yarn"
    directory: "/" # Tells Dependabot to scan root directory only
    schedule:
      interval: "daily"
    cooldown:
      default-days: 30
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 30
